"""initial migration

Revision ID: d48d378a0e52
Revises: 
Create Date: 2024-10-25 14:47:38.432329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48d378a0e52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_primary_keys_id', table_name='primary_keys')
    op.drop_table('primary_keys')
    op.drop_constraint('todos_tag_id_fkey', 'todos', type_='foreignkey')
    op.drop_column('todos', 'tag_id')
    op.add_column('union', sa.Column('id', sa.Integer(), nullable=False))
    # op.alter_column('union', 'todo_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('union', 'tag_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.create_index(op.f('ix_union_id'), 'union', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_union_id'), table_name='union')
    op.alter_column('union', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('union', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('union', 'id')
    op.add_column('todos', sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('todos_tag_id_fkey', 'todos', 'tags', ['tag_id'], ['id'])
    op.create_table('primary_keys',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='primary_keys_pkey'),
    sa.UniqueConstraint('key_name', name='primary_keys_key_name_key')
    )
    op.create_index('ix_primary_keys_id', 'primary_keys', ['id'], unique=False)
    # ### end Alembic commands ###
